chat/urls.py
from django.urls import path

from chat.views import home, signup, login_view, logout_view, chat, update_status, connect

urlpatterns = [
    path('', home, name="home"),
    path('chat/<str:room_name>', chat, name="chat"),
    path('signup/', signup, name="signup"),
    path('update-status/', update_status, name="status"),
    path('connect/', connect, name="connect"),
    path('accounts/login/', login_view, name="login"),
    path('accounts/logout/', logout_view, name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("chat.urls")),
]

chat/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from multiselectfield import MultiSelectField

INTEREST_CHOICES = (('food', 'food'),
                    ('travel', 'travel'),
                    ('movies', 'movies'),
                    ('hiking', 'hiking'),
                    ('cars', 'cars'))

GENDER = (('male', 'male'),
          ('female', 'female'),
          ('others', 'others'))


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    full_name = models.CharField(max_length=255, blank=True, default='')
    email = models.EmailField(blank=True, default='', unique=True)
    phone_number = models.CharField(max_length=30, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, default='')
    gender = models.CharField(choices=GENDER, max_length=20)
    interests = MultiSelectField(choices=INTEREST_CHOICES,
                                 max_choices=3,
                                 max_length=100)

    is_online = models.BooleanField(default=False)
    in_chat = models.BooleanField(default=False)
    is_ready = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.email

chat/forms.py
from django import forms

from .models import User


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['full_name', 'email', 'country', 'phone_number', 'gender', 'interests', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data['password']
        user.set_password(password)
        if commit:
            user.save()
        return user

chat/views.py
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect

from chat.forms import SignupForm
from chat.models import User

user = get_user_model()


@login_required
def home(request):
    if request.user is not None:
        current_user = User.objects.get(pk=request.user.pk)
        if current_user.in_chat:
            current_user.in_chat = False
        if current_user.is_ready:
            current_user.is_ready = False
        current_user.save()
    return render(request, 'home.html')


@login_required
def connect(request):
    if request.user is not None:
        current_user = User.objects.get(pk=request.user.pk)
        if not current_user.is_ready:
            current_user.is_ready = True
        if current_user.in_chat:
            current_user.in_chat = False
        current_user.save()
    return render(request, 'connect.html')


@login_required
def chat(request, room_name):
    if request.user is not None:
        current_user = User.objects.get(pk=request.user.pk)
        matched_user = User.objects.get(pk=[pk for pk in room_name.split("-") if pk != str(request.user.pk)][0])
        if not current_user.in_chat:
            current_user.in_chat = True
        if current_user.is_ready:
            current_user.is_ready = False
        current_user.save()
    return render(request, 'chat.html', {"matched_user": matched_user})


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                user.is_online = True
                user.save()
                return redirect('home')
    else:
        if request.user.is_authenticated:
            return redirect('home')
        form = AuthenticationForm()
        form.fields['username'].label = 'Email'

    return render(request, 'login.html', {'form': form})


@login_required
def logout_view(request):
    user = User.objects.filter(pk=request.user.pk).first()
    user.is_online = False
    user.in_chat = False
    user.is_ready = False
    user.save()
    logout(request)
    return redirect('login')


def update_status(request):
    user = request.GET.get("user")
    status = request.GET.get("status")
    if user is not None:
        user = User.objects.get(pk=user)
        if status == "on":
            user.is_online = True
            updated_status = "Online"
        else:
            user.is_online = False
            updated_status = "Offline"
        user.save()

    return HttpResponse(updated_status)

chat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ChatApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
            </ul>
            <div class="d-flex">
                {% if request.user.is_authenticated %}
                <form class="d-flex" action="{% url 'logout' %}">
                    <button class="btn btn-outline-success" type="submit">Logout</button>
                </form>
                {% elif request.path == '/accounts/login/' %}
                <form class="d-flex" action="{% url 'signup' %}">
                    <button class="btn btn-outline-primary" type="submit">Signup</button>
                </form>
                {% else %}
                <form class="d-flex" action="{% url 'login' %}">
                    <button class="btn btn-outline-success" type="submit">Login</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
{% block script %}
{% endblock %}
</html>

chat/templates/chat.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
.chat-log {
    height: 300px;
    overflow-y: auto;
    border: 1px solid #ccc;
    padding: 10px;
    margin-bottom: 10px;
}

.chat-form {
    display: flex;
    align-items: center;
    position: sticky;
    bottom: 0;
    background-color: #f5f5f5;
    padding: 10px;
    border-top: 1px solid #ccc;
}

.chat-form input {
    flex-grow: 1;
    margin-right: 10px;
}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="d-flex justify-content-between align-items-center">
                <h1 class="text-start">Chat Room</h1>
                <form action="{% url 'connect' %}">
                    <button id="leave-chat-button" class="btn btn-danger">Leave Chat</button>
                </form>
            </div>
            {{ request.user.full_name|json_script:"user_name" }}
            <div>
                <p>Name: {{ matched_user.full_name }}</p>
                <p>Gender: {{ matched_user.gender }}</p>
                <p>Country: {{ matched_user.country }}</p>
            </div>

            <div id="chat-log" class="chat-log">
                <!-- Display chat messages -->
            </div>

            <form id="chat-form" class="chat-form">
                <input type="text" id="chat-message-input" class="form-control" autofocus>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

chat/templates/connect.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{{ request.user.id|json_script:"user" }}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center connect">
            <h1>Connecting...</h1>
            <p>Please wait while we connect you to the chat.</p>
            <button id="refreshButton" class="btn btn-primary">Refresh</button>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/matching.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#refreshButton').click(function() {
            location.reload();
        });
    });
</script>
{% endblock %}

chat/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center">Welcome to My Chat App</h1>
            <div id="online-status" class="text-center mt-4">
                <div class="form-check form-switch d-flex justify-content-center">
                    <input class="form-check-input" type="checkbox" id="statusSwitch" name="status" checked>
                    <label class="form-check-label" for="statusSwitch" id="statusLabel">Online</label>
                </div>
            </div>
            <div class="text-center mt-4">
                <a id="joinChat" href="{% url 'connect' %}" class="btn btn-primary">Join Chat</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        var user = {{ user.pk }};
        $('#statusSwitch').change(function() {
            var isChecked = $(this).prop('checked');

            $.ajax({
                url: '/update-status/',
                method: 'GET',
                data: {
                    status: isChecked ? 'on' : 'off',
                    user: user,
                },
                success: function(response) {
                    $('#statusLabel').text(response);
                    console.log(response);
                },
                error: function(xhr, status, error) {
                    console.error(error);
                }
            });
        });
    });
</script>
{% endblock %}

chat/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Login</h2>
            <form method="post" action="{% url 'login' %}" class="mt-4">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_email">Email</label>
                    {% render_field form.username class="form-control" id="id_email" name="email" required="True" %}
                </div>

                <div class="form-group">
                    <label for="id_password">Password</label>
                    {% render_field form.password class="form-control" id="id_password" name="password" required="True" %}
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    .text-center {
        margin-top: 20px;
    }
</style>
{% endblock %}

chat/templates/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="mb-4">Sign Up</h2>
            <form method="POST" action="{% url 'signup' %}">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_full_name">Full Name</label>
                    {% render_field form.full_name class="form-control" id="id_full_name" name="full_name" required="True" %}
                </div>

                <div class="form-group">
                    <label for="id_email">Email</label>
                    {% render_field form.email class="form-control" id="id_email" name="email" required="True" %}
                </div>

                <div class="form-group">
                    <label for="id_country">Country</label>
                    {% render_field form.country class="form-control" id="id_country" name="country" %}
                </div>

                <div class="form-group">
                    <label for="id_phone_number">Phone Number</label>
                    {% render_field form.phone_number class="form-control" id="id_phone_number" name="phone_number" %}
                </div>

                <div class="form-group">
                    <label for="id_gender">Gender</label>
                    {% render_field form.gender class="form-control" id="id_gender" name="gender" %}
                </div>

                <div class="form-group">
                    <label for="id_interests">Interests</label>
                    {% render_field form.interests id="id_interests" name="interests" %}
                </div>


                <div class="form-group">
                    <label for="id_password">Password</label>
                    {% render_field form.password class="form-control" id="id_password" name="password" required="True" %}
                </div>

                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}